logging:
  level:
    ROOT: INFO
    com.sergey.didenko.spring.hqljdbc: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hqljdbc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: admin
    password: admin
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
